OULTINE OPTIMIZATION RESULTS (ON SCHOOL LAPTOP):

SAMPLING 4 NEIGHBORING PIXELS:

  AVG FPS: 55.41
  AVG CPU RENDER TIME: 0.792
  AVG GPU RENDER TIME: 14.24

SAMPLING 2 NEIGHBORING PIXELS:

  AVG FPS: 64.73
  AVG CPU RENDER TIME: 0.776
  AVG GPU RENDER TIME: 13.03

SAMPLING 3 NEIGHBORING PIXELS:

  AVG FPS: 50.25
  AVG CPU RENDER TIME: 0.815
  AVG GPU RENDER TIME: 15.21

Averages taken after ~30 seconds in the scene
